spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

security:
    token:
