spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

security:
  token:
    secret-key: ${SECRET~KEY}
    expire-length: 3600000
